import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Nav, Main } from "../styles/shared";
import { UIButton } from "../components/UIButton";

const ButtonPage: NextPage = () => {
  const handleClick = () => {
    alert("Click")
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav>
        <Link href="/" passHref>
          <UIButton as="a">Back</UIButton>
        </Link>
      </Nav>
      <Main>
        <UIButton onClick={handleClick}>Primary</UIButton>
        <UIButton onClick={handleClick} secondary>Secondary</UIButton>

        <UIButton onClick={handleClick} outline>Primary</UIButton>
        <UIButton onClick={handleClick} outline secondary>Secondary</UIButton>

        <UIButton onClick={handleClick} disabled>Primary</UIButton>
        <UIButton onClick={handleClick} disabled secondary>Secondary</UIButton>

        <UIButton onClick={handleClick} disabled outline>Primary</UIButton>
        <UIButton onClick={handleClick} disabled outline secondary>Secondary</UIButton>
      </Main>
    </>
  );
};

export default ButtonPage;
