import type { NextPage } from "next";
import Head from "next/head";
import { Main } from "../styles/shared";
import UILink from "../components/UILink";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <UILink href="/button">Buttons</UILink>
      </Main>
    </>
  );
};

export default Home;
